module.exports = {
  ROLES: ["USER", "VENDOR", "ADMIN"], 
  WASHTIMES:["NORMAL WASH", "EXPRESS WASH"],
  DELIVERY_METHOD: ["SELF DROP-OFF", "VENDOR PICK-UP"], 
  WASHTYPES:["NORMAL WASH", "DRY WASH", "OTHERS"]
}
